# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_engg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 157)
        MainWindow.setMinimumSize(QtCore.QSize(491, 157))
        MainWindow.setMaximumSize(QtCore.QSize(491, 157))
        MainWindow.setStyleSheet("*{\n"
"  font-family:century gothic;\n"
"  font-size:16px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
" background:rgba(0,0,0,0);\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"QLineEdit\n"
"{\n"
"font-size:23px;\n"
"background:rgba(0,0,0,0);\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}\n"
"QWidget\n"
"{\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 271, 41))
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 100, 271, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 110, 51, 21))
        self.pushButton.setStyleSheet("color: rgb(0, 105, 180);\n"
"font: 10pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 140, 51, 16))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(163, 10, 141, 31))
        self.label_4.setStyleSheet("background:rgba(0,0,0,0.0);\n"
"QLabel\n"
"{\n"
"background:/newPrefix/kisspng-mobile-legends-bang-bang-vivo-v7-blu-vivo-selfie-mobile-legend-5b0bcd9b0ea687.56196197152750018706.png\n"
"\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/ico/dd62b885578d13ba8a091cd4c9c57845.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 15, 21, 31))
        self.label_2.setStyleSheet("background:rgba(0,0,0,0.0);\n"
"color: rgb(85, 170, 255);\n"
"font: 23pt \"MS Shell Dlg 2\";")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/kisspng-mobile-legends-bang-bang-vivo-v7-blu-vivo-selfie-mobile-legend-5b0bcd9b0ea687.56196197152750018706.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 261, 16))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background:rgba(0,0,0,0.0);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login_engg"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "user name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "password"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "ver-2.1"))
        self.label_2.setText(_translate("MainWindow", "!"))
        self.label_3.setText(_translate("MainWindow", "\"Opps\" Invalid user name and password"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
